export enum NotificationType {
  STORY_GENERATION_STARTED = 'STORY_GENERATION_STARTED',
  STORY_PAGE_COMPLETED = 'STORY_PAGE_COMPLETED',
  STORY_GENERATION_COMPLETED = 'STORY_GENERATION_COMPLETED',
  STORY_GENERATION_PARTIALLY_FAILED = 'STORY_GENERATION_PARTIALLY_FAILED',
  STORY_GENERATION_FAILED = 'STORY_GENERATION_FAILED',
  STORY_ILLUSTRATION_FAILED = 'STORY_ILLUSTRATION_FAILED',
  STORY_DELETED = 'STORY_DELETED',
  AI_DAILY_LIMIT_REACHED = 'AI_DAILY_LIMIT_REACHED',
  STORY_SHARED = 'STORY_SHARED',
  STORY_ACCESS_REMOVED = 'STORY_ACCESS_REMOVED',
}
