export const AuditAction = {
  // Authentication
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  OTHER_SESSIONS_REVOKED: 'OTHER_SESSIONS_REVOKED',
  OTHER_USERS_SESSIONS_REVOKED: 'OTHER_USERS_SESSIONS_REVOKED',
  ALL_SESSIONS_REVOKED: 'ALL_SESSIONS_REVOKED',

  // Users
  USER_CREATED: 'USER_CREATED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  ROLE_CHANGED: 'ROLE_CHANGED',

  // Stories
  STORY_CREATED: 'STORY_CREATED',
  STORY_UPDATED: 'STORY_UPDATED',
  STORY_DELETED: 'STORY_DELETED',
  STORY_VISIBILITY_CHANGED: 'STORY_VISIBILITY_CHANGED',
  STORY_TEXT_APPENDED: 'STORY_TEXT_APPENDED',
  STORY_PAGE_UPDATED: 'STORY_PAGE_UPDATED',
  STORY_PAGE_DELETED: 'STORY_PAGE_DELETED',
  STORY_PAGE_REGENERATED: 'STORY_PAGE_REGENERATED',

  // Sharing
  STORY_SHARED: 'STORY_SHARED',
  STORY_ACCESS_REMOVED: 'STORY_ACCESS_REMOVED',

  // AI Generation
  STORY_GENERATION_STARTED: 'STORY_GENERATION_STARTED',
  STORY_GENERATION_COMPLETED: 'STORY_GENERATION_COMPLETED',
  STORY_GENERATION_FAILED: 'STORY_GENERATION_FAILED',
  GENERATION_RETRY: 'GENERATION_RETRY',

  // System (admin-only)
  AI_USAGE_RESET: 'AI_USAGE_RESET',
  QUEUE_CLEAN: 'QUEUE_CLEAN',

  // Story options (catalog management)
  STORY_GENRE_CREATED: 'STORY_GENRE_CREATED',
  STORY_GENRE_UPDATED: 'STORY_GENRE_UPDATED',
  STORY_GENRE_DEACTIVATED: 'STORY_GENRE_DEACTIVATED',
  STORY_ERA_CREATED: 'STORY_ERA_CREATED',
  STORY_ERA_UPDATED: 'STORY_ERA_UPDATED',
  STORY_ERA_DEACTIVATED: 'STORY_ERA_DEACTIVATED',
  STORY_CIVILIZATION_CREATED: 'STORY_CIVILIZATION_CREATED',
  STORY_CIVILIZATION_UPDATED: 'STORY_CIVILIZATION_UPDATED',
  STORY_CIVILIZATION_DEACTIVATED: 'STORY_CIVILIZATION_DEACTIVATED',
} as const;

export type AuditActionValue = (typeof AuditAction)[keyof typeof AuditAction];

export const AUDIT_ACTIONS_LIST: readonly AuditActionValue[] =
  Object.values(AuditAction);

export const AUDIT_ACTION_CATEGORIES = {
  authentication: [
    AuditAction.LOGIN_SUCCESS,
    AuditAction.LOGIN_FAILED,
    AuditAction.LOGOUT,
    AuditAction.REGISTER,
    AuditAction.PASSWORD_CHANGED,
    AuditAction.SESSION_REVOKED,
    AuditAction.OTHER_SESSIONS_REVOKED,
    AuditAction.OTHER_USERS_SESSIONS_REVOKED,
    AuditAction.ALL_SESSIONS_REVOKED,
  ],
  users: [
    AuditAction.USER_CREATED,
    AuditAction.USER_ACTIVATED,
    AuditAction.USER_DEACTIVATED,
    AuditAction.ROLE_CHANGED,
  ],
  stories: [
    AuditAction.STORY_CREATED,
    AuditAction.STORY_UPDATED,
    AuditAction.STORY_DELETED,
    AuditAction.STORY_VISIBILITY_CHANGED,
  ],
  sharing: [AuditAction.STORY_SHARED, AuditAction.STORY_ACCESS_REMOVED],
  generation: [
    AuditAction.STORY_GENERATION_STARTED,
    AuditAction.STORY_GENERATION_COMPLETED,
    AuditAction.STORY_GENERATION_FAILED,
    AuditAction.GENERATION_RETRY,
  ],
  system: [AuditAction.AI_USAGE_RESET, AuditAction.QUEUE_CLEAN],
} as const;
