import { StoryCivilization } from '../enums/story-civilization.enum';

/**
 * Central, data-driven registry for civilizations.
 *
 * RULES (see requirements):
 * - LANGUAGE is NOT a civilization. Language controls only visible written
 *   text; civilization controls the visual/cultural identity of the world.
 * - The backend stores stable enum values; the frontend receives human-readable
 *   labels via GET /stories/meta/civilizations.
 * - Unspecified relies on story content, location, era/year and theme.
 * - Custom (generic or regional) uses the user's customCivilization value.
 */
export type CivilizationRegion =
  | 'Unspecified'
  | 'Africa'
  | 'Middle East & Ancient Near East'
  | 'Mediterranean & Classical'
  | 'Europe'
  | 'South Asia'
  | 'East Asia'
  | 'Southeast Asia'
  | 'Central Asia'
  | 'North America'
  | 'Mesoamerica'
  | 'South America'
  | 'Oceania'
  | 'Religious-Historical'
  | 'Modern Regional'
  | 'Fantasy'
  | 'Other'
  | 'Custom';

export type CivilizationKind = 'specific' | 'other' | 'custom' | 'unspecified';

export interface CivilizationDefinition {
  value: StoryCivilization;
  label: string;
  region: CivilizationRegion;
  kind: CivilizationKind;
}

export const CIVILIZATION_REGIONS: readonly CivilizationRegion[] = [
  'Unspecified',
  'Africa',
  'Middle East & Ancient Near East',
  'Mediterranean & Classical',
  'Europe',
  'South Asia',
  'East Asia',
  'Southeast Asia',
  'Central Asia',
  'North America',
  'Mesoamerica',
  'South America',
  'Oceania',
  'Religious-Historical',
  'Modern Regional',
  'Fantasy',
  'Other',
  'Custom',
];

export const CIVILIZATIONS: readonly CivilizationDefinition[] = [
  {
    value: StoryCivilization.ANCIENT_EGYPTIAN,
    label: 'Ancient Egyptian',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.EGYPTIAN,
    label: 'Egyptian',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.NUBIAN,
    label: 'Nubian',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.KUSHITE,
    label: 'Kushite',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MEROITIC,
    label: 'Meroitic',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.AXUMITE,
    label: 'Axumite',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ETHIOPIAN,
    label: 'Ethiopian',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SOMALI,
    label: 'Somali',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.BERBER_AMAZIGH,
    label: 'Berber / Amazigh',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.CARTHAGINIAN,
    label: 'Carthaginian',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ANCIENT_NORTH_AFRICAN,
    label: 'Ancient North African',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.WEST_AFRICAN,
    label: 'West African',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.GHANA_EMPIRE,
    label: 'Ghana Empire',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MALI_EMPIRE,
    label: 'Mali Empire',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SONGHAI_EMPIRE,
    label: 'Songhai Empire',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.YORUBA,
    label: 'Yoruba',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.IGBO,
    label: 'Igbo',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.HAUSA,
    label: 'Hausa',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.BENIN_KINGDOM,
    label: 'Benin Kingdom',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ASHANTI,
    label: 'Ashanti',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.KONGO,
    label: 'Kongo',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.GREAT_ZIMBABWE,
    label: 'Great Zimbabwe',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SWAHILI_COAST,
    label: 'Swahili Coast',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ZULU,
    label: 'Zulu',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.XHOSA,
    label: 'Xhosa',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MAASAI,
    label: 'Maasai',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TUAREG,
    label: 'Tuareg',
    region: 'Africa',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_AFRICAN,
    label: 'Other African',
    region: 'Africa',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_AFRICAN_CIVILIZATION,
    label: 'Custom African Civilization',
    region: 'Africa',
    kind: 'custom',
  },
  {
    value: StoryCivilization.ARABIC,
    label: 'Arabic',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SUMERIAN,
    label: 'Sumerian',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.AKKADIAN,
    label: 'Akkadian',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.BABYLONIAN,
    label: 'Babylonian',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ASSYRIAN,
    label: 'Assyrian',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.PERSIAN,
    label: 'Persian',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ACHAEMENID_PERSIAN,
    label: 'Achaemenid Persian',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SASANIAN_PERSIAN,
    label: 'Sasanian Persian',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MEDIAN,
    label: 'Median',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ELAMITE,
    label: 'Elamite',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.HITTITE,
    label: 'Hittite',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.PHOENICIAN,
    label: 'Phoenician',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.CANAANITE,
    label: 'Canaanite',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ANCIENT_LEVANTINE,
    label: 'Ancient Levantine',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ARAMAEAN,
    label: 'Aramaean',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.NABATAEAN,
    label: 'Nabataean',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.UGARITIC,
    label: 'Ugaritic',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MESOPOTAMIAN,
    label: 'Mesopotamian',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ARABIAN,
    label: 'Arabian',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.PRE_ISLAMIC_ARABIAN,
    label: 'Pre-Islamic Arabian',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ISLAMIC_ARABIAN,
    label: 'Islamic Arabian',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ABBASID,
    label: 'Abbasid',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.UMAYYAD,
    label: 'Umayyad',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.FATIMID,
    label: 'Fatimid',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MAMLUK,
    label: 'Mamluk',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTTOMAN,
    label: 'Ottoman',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.LEVANTINE,
    label: 'Levantine',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.KURDISH,
    label: 'Kurdish',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ARMENIAN,
    label: 'Armenian',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.GEORGIAN,
    label: 'Georgian',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MESOPOTAMIAN_ARAB,
    label: 'Mesopotamian Arab',
    region: 'Middle East & Ancient Near East',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_MIDDLE_EASTERN,
    label: 'Other Middle Eastern',
    region: 'Middle East & Ancient Near East',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_MIDDLE_EASTERN_CIVILIZATION,
    label: 'Custom Middle Eastern Civilization',
    region: 'Middle East & Ancient Near East',
    kind: 'custom',
  },
  {
    value: StoryCivilization.ANCIENT_GREEK,
    label: 'Ancient Greek',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.GREEK,
    label: 'Greek',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ROMAN,
    label: 'Roman',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MYCENAEAN_GREEK,
    label: 'Mycenaean Greek',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MINOAN,
    label: 'Minoan',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.CLASSICAL_GREEK,
    label: 'Classical Greek',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.HELLENISTIC,
    label: 'Hellenistic',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SPARTAN,
    label: 'Spartan',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ATHENIAN,
    label: 'Athenian',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MACEDONIAN,
    label: 'Macedonian',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ANCIENT_ROMAN,
    label: 'Ancient Roman',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ROMAN_REPUBLIC,
    label: 'Roman Republic',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ROMAN_EMPIRE,
    label: 'Roman Empire',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.BYZANTINE,
    label: 'Byzantine',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ETRUSCAN,
    label: 'Etruscan',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ILLYRIAN,
    label: 'Illyrian',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.THRACIAN,
    label: 'Thracian',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.DACIAN,
    label: 'Dacian',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.CELTIC,
    label: 'Celtic',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.PHOENICIAN_MEDITERRANEAN,
    label: 'Phoenician Mediterranean',
    region: 'Mediterranean & Classical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_MEDITERRANEAN,
    label: 'Other Mediterranean',
    region: 'Mediterranean & Classical',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_MEDITERRANEAN_CIVILIZATION,
    label: 'Custom Mediterranean Civilization',
    region: 'Mediterranean & Classical',
    kind: 'custom',
  },
  {
    value: StoryCivilization.ANGLO_SAXON,
    label: 'Anglo-Saxon',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.VIKING_NORSE,
    label: 'Viking / Norse',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MEDIEVAL_ENGLISH,
    label: 'Medieval English',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MEDIEVAL_FRENCH,
    label: 'Medieval French',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MEDIEVAL_GERMANIC,
    label: 'Medieval Germanic',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MEDIEVAL_SPANISH,
    label: 'Medieval Spanish',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MEDIEVAL_PORTUGUESE,
    label: 'Medieval Portuguese',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MEDIEVAL_ITALIAN,
    label: 'Medieval Italian',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MEDIEVAL_SCANDINAVIAN,
    label: 'Medieval Scandinavian',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MEDIEVAL_SLAVIC,
    label: 'Medieval Slavic',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.RUSSIAN,
    label: 'Russian',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.KIEVAN_RUS,
    label: 'Kievan Rus',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.POLISH,
    label: 'Polish',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.BOHEMIAN,
    label: 'Bohemian',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.HUNGARIAN,
    label: 'Hungarian',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.BALKAN,
    label: 'Balkan',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.VENETIAN,
    label: 'Venetian',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.RENAISSANCE_ITALIAN,
    label: 'Renaissance Italian',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.RENAISSANCE_EUROPEAN,
    label: 'Renaissance European',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.VICTORIAN_BRITISH,
    label: 'Victorian British',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.GEORGIAN_BRITISH,
    label: 'Georgian British',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.EDWARDIAN_BRITISH,
    label: 'Edwardian British',
    region: 'Europe',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_EUROPEAN,
    label: 'Other European',
    region: 'Europe',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_EUROPEAN_CIVILIZATION,
    label: 'Custom European Civilization',
    region: 'Europe',
    kind: 'custom',
  },
  {
    value: StoryCivilization.INDUS_VALLEY,
    label: 'Indus Valley',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.VEDIC,
    label: 'Vedic',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ANCIENT_INDIAN,
    label: 'Ancient Indian',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MAURYAN,
    label: 'Mauryan',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.GUPTA,
    label: 'Gupta',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.CHOLA,
    label: 'Chola',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.PALLAVA,
    label: 'Pallava',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MUGHAL,
    label: 'Mughal',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.RAJPUT,
    label: 'Rajput',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MARATHA,
    label: 'Maratha',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.VIJAYANAGARA,
    label: 'Vijayanagara',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.BENGALI,
    label: 'Bengali',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.PUNJABI,
    label: 'Punjabi',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TAMIL,
    label: 'Tamil',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TELUGU,
    label: 'Telugu',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SINHALA,
    label: 'Sinhala',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.NEPALESE,
    label: 'Nepalese',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TIBETAN,
    label: 'Tibetan',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.KASHMIRI,
    label: 'Kashmiri',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.INDO_ISLAMIC,
    label: 'Indo-Islamic',
    region: 'South Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_SOUTH_ASIAN,
    label: 'Other South Asian',
    region: 'South Asia',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_SOUTH_ASIAN_CIVILIZATION,
    label: 'Custom South Asian Civilization',
    region: 'South Asia',
    kind: 'custom',
  },
  {
    value: StoryCivilization.ANCIENT_CHINESE,
    label: 'Ancient Chinese',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SHANG,
    label: 'Shang',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ZHOU,
    label: 'Zhou',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.QIN,
    label: 'Qin',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.HAN,
    label: 'Han',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.THREE_KINGDOMS_CHINA,
    label: 'Three Kingdoms China',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TANG,
    label: 'Tang',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SONG,
    label: 'Song',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.YUAN,
    label: 'Yuan',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MING,
    label: 'Ming',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.QING,
    label: 'Qing',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.IMPERIAL_CHINESE,
    label: 'Imperial Chinese',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ANCIENT_JAPANESE,
    label: 'Ancient Japanese',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.HEIAN_JAPANESE,
    label: 'Heian Japanese',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.KAMAKURA_JAPANESE,
    label: 'Kamakura Japanese',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MUROMACHI_JAPANESE,
    label: 'Muromachi Japanese',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.EDO_JAPANESE,
    label: 'Edo Japanese',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SAMURAI_JAPAN,
    label: 'Samurai Japan',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ANCIENT_KOREAN,
    label: 'Ancient Korean',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.GOGURYEO,
    label: 'Goguryeo',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.BAEKJE,
    label: 'Baekje',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SILLA,
    label: 'Silla',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.GORYEO,
    label: 'Goryeo',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.JOSEON,
    label: 'Joseon',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MONGOLIAN,
    label: 'Mongolian',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MANCHU,
    label: 'Manchu',
    region: 'East Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_EAST_ASIAN,
    label: 'Other East Asian',
    region: 'East Asia',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_EAST_ASIAN_CIVILIZATION,
    label: 'Custom East Asian Civilization',
    region: 'East Asia',
    kind: 'custom',
  },
  {
    value: StoryCivilization.KHMER,
    label: 'Khmer',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ANGKOR,
    label: 'Angkor',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SRIVIJAYA,
    label: 'Srivijaya',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MAJAPAHIT,
    label: 'Majapahit',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.CHAMPA,
    label: 'Champa',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.PAGAN_BAGAN,
    label: 'Pagan / Bagan',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.BURMESE,
    label: 'Burmese',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.THAI_SIAMESE,
    label: 'Thai / Siamese',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.AYUTTHAYA,
    label: 'Ayutthaya',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.VIETNAMESE,
    label: 'Vietnamese',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.DAI_VIET,
    label: 'Dai Viet',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MALAY,
    label: 'Malay',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.INDONESIAN,
    label: 'Indonesian',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.JAVANESE,
    label: 'Javanese',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.BALINESE,
    label: 'Balinese',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.FILIPINO_PRECOLONIAL_PHILIPPINE,
    label: 'Filipino / Precolonial Philippine',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.LAO,
    label: 'Lao',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.CAMBODIAN,
    label: 'Cambodian',
    region: 'Southeast Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_SOUTHEAST_ASIAN,
    label: 'Other Southeast Asian',
    region: 'Southeast Asia',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_SOUTHEAST_ASIAN_CIVILIZATION,
    label: 'Custom Southeast Asian Civilization',
    region: 'Southeast Asia',
    kind: 'custom',
  },
  {
    value: StoryCivilization.SCYTHIAN,
    label: 'Scythian',
    region: 'Central Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SARMATIAN,
    label: 'Sarmatian',
    region: 'Central Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.HUNNIC,
    label: 'Hunnic',
    region: 'Central Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TURKIC,
    label: 'Turkic',
    region: 'Central Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.GOKTURK,
    label: 'Göktürk',
    region: 'Central Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MONGOL,
    label: 'Mongol',
    region: 'Central Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MONGOL_EMPIRE,
    label: 'Mongol Empire',
    region: 'Central Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TIMURID,
    label: 'Timurid',
    region: 'Central Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.UZBEK,
    label: 'Uzbek',
    region: 'Central Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.KAZAKH,
    label: 'Kazakh',
    region: 'Central Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.KYRGYZ,
    label: 'Kyrgyz',
    region: 'Central Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.UYGHUR,
    label: 'Uyghur',
    region: 'Central Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.PERSIANATE_CENTRAL_ASIAN,
    label: 'Persianate Central Asian',
    region: 'Central Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SILK_ROAD,
    label: 'Silk Road',
    region: 'Central Asia',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_CENTRAL_ASIAN,
    label: 'Other Central Asian',
    region: 'Central Asia',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_CENTRAL_ASIAN_CIVILIZATION,
    label: 'Custom Central Asian Civilization',
    region: 'Central Asia',
    kind: 'custom',
  },
  {
    value: StoryCivilization.INUIT,
    label: 'Inuit',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.YUPIK,
    label: 'Yupik',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.HAIDA,
    label: 'Haida',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TLINGIT,
    label: 'Tlingit',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.IROQUOIS_HAUDENOSAUNEE,
    label: 'Iroquois / Haudenosaunee',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.CHEROKEE,
    label: 'Cherokee',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.CHOCTAW,
    label: 'Choctaw',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.LAKOTA,
    label: 'Lakota',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SIOUX,
    label: 'Sioux',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.NAVAJO_DINE,
    label: 'Navajo / Diné',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.HOPI,
    label: 'Hopi',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.PUEBLO,
    label: 'Pueblo',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MISSISSIPPIAN,
    label: 'Mississippian',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ANCESTRAL_PUEBLOAN,
    label: 'Ancestral Puebloan',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.PACIFIC_NORTHWEST_INDIGENOUS,
    label: 'Pacific Northwest Indigenous',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.GREAT_PLAINS_INDIGENOUS,
    label: 'Great Plains Indigenous',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.WOODLAND_INDIGENOUS,
    label: 'Woodland Indigenous',
    region: 'North America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_INDIGENOUS_NORTH_AMERICAN,
    label: 'Other Indigenous North American',
    region: 'North America',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_INDIGENOUS_NORTH_AMERICAN,
    label: 'Custom Indigenous North American',
    region: 'North America',
    kind: 'custom',
  },
  {
    value: StoryCivilization.OLMEC,
    label: 'Olmec',
    region: 'Mesoamerica',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MAYA,
    label: 'Maya',
    region: 'Mesoamerica',
    kind: 'specific',
  },
  {
    value: StoryCivilization.AZTEC_MEXICA,
    label: 'Aztec / Mexica',
    region: 'Mesoamerica',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TOLTEC,
    label: 'Toltec',
    region: 'Mesoamerica',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TEOTIHUACAN,
    label: 'Teotihuacan',
    region: 'Mesoamerica',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ZAPOTEC,
    label: 'Zapotec',
    region: 'Mesoamerica',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MIXTEC,
    label: 'Mixtec',
    region: 'Mesoamerica',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TARASCAN_PUREPECHA,
    label: 'Tarascan / Purépecha',
    region: 'Mesoamerica',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MESOAMERICAN,
    label: 'Mesoamerican',
    region: 'Mesoamerica',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_MESOAMERICAN,
    label: 'Other Mesoamerican',
    region: 'Mesoamerica',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_MESOAMERICAN_CIVILIZATION,
    label: 'Custom Mesoamerican Civilization',
    region: 'Mesoamerica',
    kind: 'custom',
  },
  {
    value: StoryCivilization.INCA,
    label: 'Inca',
    region: 'South America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MOCHE,
    label: 'Moche',
    region: 'South America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.NAZCA,
    label: 'Nazca',
    region: 'South America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.CHIMU,
    label: 'Chimú',
    region: 'South America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TIWANAKU,
    label: 'Tiwanaku',
    region: 'South America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.WARI,
    label: 'Wari',
    region: 'South America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MAPUCHE,
    label: 'Mapuche',
    region: 'South America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ARAWAK,
    label: 'Arawak',
    region: 'South America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TUPI,
    label: 'Tupi',
    region: 'South America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.GUARANI,
    label: 'Guarani',
    region: 'South America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ANDEAN,
    label: 'Andean',
    region: 'South America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.AMAZONIAN_INDIGENOUS,
    label: 'Amazonian Indigenous',
    region: 'South America',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_SOUTH_AMERICAN_INDIGENOUS,
    label: 'Other South American Indigenous',
    region: 'South America',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_SOUTH_AMERICAN_CIVILIZATION,
    label: 'Custom South American Civilization',
    region: 'South America',
    kind: 'custom',
  },
  {
    value: StoryCivilization.POLYNESIAN,
    label: 'Polynesian',
    region: 'Oceania',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MAORI,
    label: 'Māori',
    region: 'Oceania',
    kind: 'specific',
  },
  {
    value: StoryCivilization.HAWAIIAN,
    label: 'Hawaiian',
    region: 'Oceania',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SAMOAN,
    label: 'Samoan',
    region: 'Oceania',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TONGAN,
    label: 'Tongan',
    region: 'Oceania',
    kind: 'specific',
  },
  {
    value: StoryCivilization.TAHITIAN,
    label: 'Tahitian',
    region: 'Oceania',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MICRONESIAN,
    label: 'Micronesian',
    region: 'Oceania',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MELANESIAN,
    label: 'Melanesian',
    region: 'Oceania',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ABORIGINAL_AUSTRALIAN,
    label: 'Aboriginal Australian',
    region: 'Oceania',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_PACIFIC_ISLANDER,
    label: 'Other Pacific Islander',
    region: 'Oceania',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_OCEANIAN_CIVILIZATION,
    label: 'Custom Oceanian Civilization',
    region: 'Oceania',
    kind: 'custom',
  },
  {
    value: StoryCivilization.EARLY_ISLAMIC,
    label: 'Early Islamic',
    region: 'Religious-Historical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MEDIEVAL_ISLAMIC,
    label: 'Medieval Islamic',
    region: 'Religious-Historical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.EARLY_CHRISTIAN,
    label: 'Early Christian',
    region: 'Religious-Historical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MEDIEVAL_CHRISTIAN_EUROPE,
    label: 'Medieval Christian Europe',
    region: 'Religious-Historical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.BYZANTINE_CHRISTIAN,
    label: 'Byzantine Christian',
    region: 'Religious-Historical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ANCIENT_JEWISH_ISRAELITE,
    label: 'Ancient Jewish / Israelite',
    region: 'Religious-Historical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SECOND_TEMPLE_JEWISH,
    label: 'Second Temple Jewish',
    region: 'Religious-Historical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ANCIENT_HEBREW,
    label: 'Ancient Hebrew',
    region: 'Religious-Historical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ZOROASTRIAN_PERSIAN,
    label: 'Zoroastrian Persian',
    region: 'Religious-Historical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.BUDDHIST,
    label: 'Buddhist',
    region: 'Religious-Historical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.HINDU,
    label: 'Hindu',
    region: 'Religious-Historical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.JAIN,
    label: 'Jain',
    region: 'Religious-Historical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SIKH,
    label: 'Sikh',
    region: 'Religious-Historical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.SHINTO_JAPANESE,
    label: 'Shinto Japanese',
    region: 'Religious-Historical',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_RELIGIOUS_HISTORICAL,
    label: 'Other Religious-Historical',
    region: 'Religious-Historical',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_RELIGIOUS_HISTORICAL,
    label: 'Custom Religious-Historical',
    region: 'Religious-Historical',
    kind: 'custom',
  },
  {
    value: StoryCivilization.MODERN_EGYPTIAN,
    label: 'Modern Egyptian',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_ARABIC,
    label: 'Modern Arabic',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_TURKISH,
    label: 'Modern Turkish',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_PERSIAN,
    label: 'Modern Persian',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_GREEK,
    label: 'Modern Greek',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_ITALIAN,
    label: 'Modern Italian',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_FRENCH,
    label: 'Modern French',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_BRITISH,
    label: 'Modern British',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_SPANISH,
    label: 'Modern Spanish',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_INDIAN,
    label: 'Modern Indian',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_CHINESE,
    label: 'Modern Chinese',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_JAPANESE,
    label: 'Modern Japanese',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_KOREAN,
    label: 'Modern Korean',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_SOUTHEAST_ASIAN,
    label: 'Modern Southeast Asian',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_AFRICAN,
    label: 'Modern African',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_LATIN_AMERICAN,
    label: 'Modern Latin American',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_NORTH_AMERICAN,
    label: 'Modern North American',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_SOUTH_AMERICAN,
    label: 'Modern South American',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_EUROPEAN,
    label: 'Modern European',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_MIDDLE_EASTERN,
    label: 'Modern Middle Eastern',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_ASIAN,
    label: 'Modern Asian',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MODERN_GLOBAL,
    label: 'Modern Global',
    region: 'Modern Regional',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_MODERN_REGIONAL,
    label: 'Other Modern Regional',
    region: 'Modern Regional',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_MODERN_CIVILIZATION,
    label: 'Custom Modern Civilization',
    region: 'Modern Regional',
    kind: 'custom',
  },
  {
    value: StoryCivilization.HIGH_FANTASY,
    label: 'High Fantasy',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MEDIEVAL_FANTASY,
    label: 'Medieval Fantasy',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.DARK_FANTASY,
    label: 'Dark Fantasy',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ARABIAN_FANTASY,
    label: 'Arabian Fantasy',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.EGYPTIAN_FANTASY,
    label: 'Egyptian Fantasy',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.GREEK_FANTASY,
    label: 'Greek Fantasy',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ROMAN_FANTASY,
    label: 'Roman Fantasy',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.NORSE_FANTASY,
    label: 'Norse Fantasy',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.CELTIC_FANTASY,
    label: 'Celtic Fantasy',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ASIAN_FANTASY,
    label: 'Asian Fantasy',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.AFRICAN_FANTASY,
    label: 'African Fantasy',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.DESERT_FANTASY,
    label: 'Desert Fantasy',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MYTHOLOGICAL_FANTASY,
    label: 'Mythological Fantasy',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.STEAMPUNK_CIVILIZATION,
    label: 'Steampunk Civilization',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MIDDLE_EARTH,
    label: 'Middle-earth',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.HOBBIT,
    label: 'Hobbit',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.GONDOR,
    label: 'Gondor',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ROHAN,
    label: 'Rohan',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.MORDOR,
    label: 'Mordor',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ELVEN_MIDDLE_EARTH,
    label: 'Elven (Middle-earth)',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.DWARVEN_MIDDLE_EARTH,
    label: 'Dwarven (Middle-earth)',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ISENGARD,
    label: 'Isengard',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.NUMENOREAN,
    label: 'Númenórean',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.GONDORIAN,
    label: 'Gondorian',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ROHIRRIM,
    label: 'Rohirrim',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.ORC_MIDDLE_EARTH,
    label: 'Orc (Middle-earth)',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.URUK_HAI,
    label: 'Uruk-hai',
    region: 'Fantasy',
    kind: 'specific',
  },
  {
    value: StoryCivilization.OTHER_MIDDLE_EARTH,
    label: 'Other Middle-earth',
    region: 'Fantasy',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM_MIDDLE_EARTH,
    label: 'Custom Middle-earth',
    region: 'Fantasy',
    kind: 'custom',
  },
  {
    value: StoryCivilization.CUSTOM_FANTASY_CIVILIZATION,
    label: 'Custom Fantasy Civilization',
    region: 'Fantasy',
    kind: 'custom',
  },
  {
    value: StoryCivilization.OTHER,
    label: 'Other',
    region: 'Other',
    kind: 'other',
  },
  {
    value: StoryCivilization.CUSTOM,
    label: 'Custom',
    region: 'Custom',
    kind: 'custom',
  },
  {
    value: StoryCivilization.UNSPECIFIED,
    label: 'Unspecified',
    region: 'Unspecified',
    kind: 'unspecified',
  },
];

const BY_VALUE: ReadonlyMap<StoryCivilization, CivilizationDefinition> =
  new Map(CIVILIZATIONS.map((c) => [c.value, c]));

export function getCivilization(
  value: StoryCivilization | null | undefined,
): CivilizationDefinition | null {
  if (value === null || value === undefined) return null;
  return BY_VALUE.get(value) ?? null;
}

export function getCivilizationLabel(
  value: StoryCivilization | null | undefined,
): string | null {
  const def = getCivilization(value);
  if (!def) return null;
  if (def.kind === 'custom' && def.value !== StoryCivilization.CUSTOM) {
    return def.label;
  }
  return def.value === StoryCivilization.CUSTOM ? 'Custom' : def.label;
}

export function isCustomCivilization(
  value: StoryCivilization | null | undefined,
): boolean {
  return getCivilization(value)?.kind === 'custom';
}

export function getCivilizationsByRegion(
  region: CivilizationRegion,
): readonly CivilizationDefinition[] {
  return CIVILIZATIONS.filter((c) => c.region === region);
}
