export enum GenerationStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  GENERATING = 'GENERATING',
  UPLOADING = 'UPLOADING',
  COMPLETED = 'COMPLETED',
  PARTIALLY_FAILED = 'PARTIALLY_FAILED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
