export enum StoryTheme {
  FANTASY = 'FANTASY',
  HISTORICAL = 'HISTORICAL',
  ADVENTURE = 'ADVENTURE',
  ROMANCE = 'ROMANCE',
  MYSTERY = 'MYSTERY',
  WAR = 'WAR',
  HORROR = 'HORROR',
  COMEDY = 'COMEDY',
  DRAMA = 'DRAMA',
  MYTHOLOGY = 'MYTHOLOGY',
  RELIGIOUS = 'RELIGIOUS',
  EPIC_ADVENTURE = 'EPIC_ADVENTURE',
  HEROIC_FANTASY = 'HEROIC_FANTASY',
  MYTHIC_ADVENTURE = 'MYTHIC_ADVENTURE',
  DARK_ADVENTURE = 'DARK_ADVENTURE',
  CUSTOM = 'CUSTOM',
  UNSPECIFIED = 'UNSPECIFIED',
}

export const STORY_THEME_VALUES: StoryTheme[] = Object.values(StoryTheme);
